version: '3.8'

services:
  app:
    build: ./backend
    working_dir: /code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
